// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gossip.proto

package gossip

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqInfo struct {
	Id                   *ReqId   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body                 *ReqBody `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqInfo) Reset()         { *m = ReqInfo{} }
func (m *ReqInfo) String() string { return proto.CompactTextString(m) }
func (*ReqInfo) ProtoMessage()    {}
func (*ReqInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{0}
}

func (m *ReqInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqInfo.Unmarshal(m, b)
}
func (m *ReqInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqInfo.Marshal(b, m, deterministic)
}
func (m *ReqInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqInfo.Merge(m, src)
}
func (m *ReqInfo) XXX_Size() int {
	return xxx_messageInfo_ReqInfo.Size(m)
}
func (m *ReqInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqInfo proto.InternalMessageInfo

func (m *ReqInfo) GetId() *ReqId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ReqInfo) GetBody() *ReqBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type ReqId struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqId) Reset()         { *m = ReqId{} }
func (m *ReqId) String() string { return proto.CompactTextString(m) }
func (*ReqId) ProtoMessage()    {}
func (*ReqId) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{1}
}

func (m *ReqId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqId.Unmarshal(m, b)
}
func (m *ReqId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqId.Marshal(b, m, deterministic)
}
func (m *ReqId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqId.Merge(m, src)
}
func (m *ReqId) XXX_Size() int {
	return xxx_messageInfo_ReqId.Size(m)
}
func (m *ReqId) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqId.DiscardUnknown(m)
}

var xxx_messageInfo_ReqId proto.InternalMessageInfo

func (m *ReqId) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ReqBody struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBody) Reset()         { *m = ReqBody{} }
func (m *ReqBody) String() string { return proto.CompactTextString(m) }
func (*ReqBody) ProtoMessage()    {}
func (*ReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{2}
}

func (m *ReqBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBody.Unmarshal(m, b)
}
func (m *ReqBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBody.Marshal(b, m, deterministic)
}
func (m *ReqBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBody.Merge(m, src)
}
func (m *ReqBody) XXX_Size() int {
	return xxx_messageInfo_ReqBody.Size(m)
}
func (m *ReqBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBody.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBody proto.InternalMessageInfo

func (m *ReqBody) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Bool struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{3}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{4}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ReqInfo)(nil), "ReqInfo")
	proto.RegisterType((*ReqId)(nil), "ReqId")
	proto.RegisterType((*ReqBody)(nil), "ReqBody")
	proto.RegisterType((*Bool)(nil), "Bool")
	proto.RegisterType((*Void)(nil), "Void")
}

func init() { proto.RegisterFile("gossip.proto", fileDescriptor_878fa4887b90140c) }

var fileDescriptor_878fa4887b90140c = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8f, 0xbf, 0x6f, 0x83, 0x30,
	0x10, 0x85, 0x01, 0x19, 0x17, 0x5d, 0x99, 0x6e, 0xa0, 0x94, 0xfe, 0x50, 0xe5, 0xa9, 0x93, 0x07,
	0xba, 0x56, 0x8a, 0xc4, 0x12, 0x65, 0x43, 0x1e, 0xb2, 0x83, 0x4c, 0x82, 0x95, 0x28, 0x47, 0x62,
	0x18, 0xf8, 0xef, 0x23, 0x9f, 0xd8, 0xec, 0xfb, 0xee, 0x3e, 0xbd, 0x07, 0xf9, 0x99, 0xbc, 0x77,
	0x93, 0x9e, 0x1e, 0x34, 0x93, 0xda, 0xc1, 0x8b, 0x19, 0xee, 0x87, 0xdb, 0x89, 0xb0, 0x80, 0xc4,
	0xd9, 0x32, 0xfe, 0x89, 0x7f, 0x5f, 0x6b, 0xa9, 0xc3, 0xd4, 0x9a, 0xc4, 0x59, 0xfc, 0x04, 0xd1,
	0x93, 0x5d, 0xcb, 0x84, 0x49, 0x16, 0x48, 0x43, 0x76, 0x35, 0x3c, 0x55, 0x1f, 0x90, 0xf2, 0x2a,
	0x22, 0x88, 0xb1, 0xf3, 0x23, 0x0b, 0x72, 0xc3, 0x6f, 0xf5, 0xc5, 0xf6, 0xb0, 0x1d, 0x30, 0x5b,
	0x36, 0xcc, 0xb7, 0xdf, 0x20, 0x1a, 0xa2, 0x2b, 0x16, 0x20, 0xfd, 0xdc, 0xcd, 0x8b, 0x67, 0x9a,
	0x99, 0xed, 0xa7, 0x24, 0x88, 0x23, 0x39, 0x5b, 0xff, 0x83, 0xdc, 0x73, 0x68, 0x7c, 0x03, 0xd1,
	0xd2, 0x65, 0xc0, 0x2d, 0x5f, 0x95, 0xea, 0x20, 0x50, 0x11, 0xbe, 0x83, 0x68, 0x17, 0x3f, 0x22,
	0xc7, 0x0b, 0x75, 0xaa, 0x54, 0x87, 0x5b, 0x15, 0xf5, 0x92, 0x9b, 0xfe, 0x3d, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x08, 0xf7, 0xa6, 0xea, 0xf9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GossipClient is the client API for Gossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GossipClient interface {
	//checks whether hash already exists
	Poke(ctx context.Context, in *ReqId, opts ...grpc.CallOption) (*Bool, error)
	//sends new info
	Push(ctx context.Context, in *ReqInfo, opts ...grpc.CallOption) (*Void, error)
}

type gossipClient struct {
	cc *grpc.ClientConn
}

func NewGossipClient(cc *grpc.ClientConn) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) Poke(ctx context.Context, in *ReqId, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/Gossip/Poke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) Push(ctx context.Context, in *ReqInfo, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/Gossip/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GossipServer is the server API for Gossip service.
type GossipServer interface {
	//checks whether hash already exists
	Poke(context.Context, *ReqId) (*Bool, error)
	//sends new info
	Push(context.Context, *ReqInfo) (*Void, error)
}

// UnimplementedGossipServer can be embedded to have forward compatible implementations.
type UnimplementedGossipServer struct {
}

func (*UnimplementedGossipServer) Poke(ctx context.Context, req *ReqId) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poke not implemented")
}
func (*UnimplementedGossipServer) Push(ctx context.Context, req *ReqInfo) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}

func RegisterGossipServer(s *grpc.Server, srv GossipServer) {
	s.RegisterService(&_Gossip_serviceDesc, srv)
}

func _Gossip_Poke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Poke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gossip/Poke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Poke(ctx, req.(*ReqId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gossip/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Push(ctx, req.(*ReqInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Poke",
			Handler:    _Gossip_Poke_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _Gossip_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gossip.proto",
}
